### ISSUE TITLE
Build out purge logic

### ISSUE THREAD

**Issue by jaredledvina** [jaredledvina/sensu-client#15]
Currently, this role manages a lot of files in `/etc/sensu/conf.d/` however, if you defined a:
```
sensu_client_checks:
  sensu-website:
    command: check-http.rb -u https://sensuapp.org
    subscribers:
      - all
    interval: 60
```

And then remove `sensu_client_checks:sensu-website`, the `/etc/sensu/conf.d/check_sensu-website.json`  file remains on the remote host. Ideally, it'd get removed.
